version: '3'

services:
  mysql:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: resourcedb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  your_service_name:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/resourcedb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://172.18.5.20:8761/eureka
      AWS_ACCESS_KEY: 
      AWS_SECRET_KEY: 
    depends_on:
      - mysql
    restart: always


volumes:
  mysql_data:

